import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const poppins = Poppins({
  subsets:['latin'],
  weight:['400','700']
})

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
